package com.its.servers.facade.cxf.sys.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-05-26T11:23:24.615+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.sys.cxf.facade.servers.its.com/", name = "CXFSysUserFacade")
@XmlSeeAlso({ObjectFactory.class})
public interface CXFSysUserFacade {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSysUserList", targetNamespace = "http://service.sys.cxf.facade.servers.its.com/", className = "com.its.servers.facade.cxf.sys.service.GetSysUserList")
    @WebMethod
    @ResponseWrapper(localName = "getSysUserListResponse", targetNamespace = "http://service.sys.cxf.facade.servers.its.com/", className = "com.its.servers.facade.cxf.sys.service.GetSysUserListResponse")
    public java.util.List<com.its.servers.facade.cxf.sys.service.SysUser> getSysUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Integer arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSysUserCount", targetNamespace = "http://service.sys.cxf.facade.servers.its.com/", className = "com.its.servers.facade.cxf.sys.service.GetSysUserCount")
    @WebMethod
    @ResponseWrapper(localName = "getSysUserCountResponse", targetNamespace = "http://service.sys.cxf.facade.servers.its.com/", className = "com.its.servers.facade.cxf.sys.service.GetSysUserCountResponse")
    public int getSysUserCount(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
