package com.its.servers.facade.cxf.sys.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.its.servers.facade.cxf.sys.service.CXFSysUserFacade;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-05-26T11:23:24.664+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "cxfSysUserFacadeImpl", 
                  wsdlLocation = "http://127.0.0.1:8080/cxf/cxfSysUserFacade?wsdl",
                  targetNamespace = "http://impl.service.sys.cxf.facade.servers.its.com/") 
public class CxfSysUserFacadeImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.sys.cxf.facade.servers.its.com/", "cxfSysUserFacadeImpl");
    public final static QName CXFSysUserFacadeImplPort = new QName("http://impl.service.sys.cxf.facade.servers.its.com/", "CXFSysUserFacadeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/cxf/cxfSysUserFacade?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfSysUserFacadeImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/cxf/cxfSysUserFacade?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfSysUserFacadeImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfSysUserFacadeImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfSysUserFacadeImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CxfSysUserFacadeImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CxfSysUserFacadeImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CxfSysUserFacadeImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CXFSysUserFacade
     */
    @WebEndpoint(name = "CXFSysUserFacadeImplPort")
    public CXFSysUserFacade getCXFSysUserFacadeImplPort() {
        return super.getPort(CXFSysUserFacadeImplPort, CXFSysUserFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CXFSysUserFacade
     */
    @WebEndpoint(name = "CXFSysUserFacadeImplPort")
    public CXFSysUserFacade getCXFSysUserFacadeImplPort(WebServiceFeature... features) {
        return super.getPort(CXFSysUserFacadeImplPort, CXFSysUserFacade.class, features);
    }

}
